# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build the application
FROM node:22-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the application source code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Create a production image
FROM node:22-alpine

# Set the working directory
WORKDIR /app

# Copy the built application from the builder stage
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./

# Install only production dependencies
RUN npm install --omit=dev --ignore-scripts

# Expose necessary port (if required by the server)
EXPOSE 8080

# Set the environment variable for API key
ENV ATTIO_API_KEY=your_attio_api_key_here

# Start the application
ENTRYPOINT ["node", "dist/index.js"]
